version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-tcc-dev:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'

  # app1: &app1
  #   hostname: app1
  #   stdin_open: true
  #   build:
  #     context: .
  #   restart: always
  #   depends_on:
  #     - postgres
  #   # expose:
  #     # - "3000"
  #   ports:
  #     - 3000:3000
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     JWT_SECRET: ${JWT_SECRET}
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: '0.25GB'

  # app2:
  #   <<: *app1
  #   hostname: app2

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app1
  #     - app2
  #   ports:
  #     - "3000:3000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: '0.25GB'
  
volumes:
  postgres-tcc-dev:
